### ISSUE TITLE
How to add Remove function?

### ISSUE THREAD

**Issue by graup** [NeekSandhu/react-aspen-demo#4]
First off, thanks for this library, must have been a lot of work.

I tried to add a "Remove" button to the entries (both directory and files) using:
```js
this.props.model.root.inotify({
    type: WatchEvent.Removed,
    path: item.path,
});
```

But this fails with this exception:
```
Uncaught (in promise) TypeError: Method WeakMap.prototype.delete called on incompatible receiver undefined
    at delete (<anonymous>)
    at index.js:40
    at Set.forEach (<anonymous>)
    at Notificar.dispatch (index.js:40)
    at Object.notifyDidDispose (Root.js:52)
    at FileEntry.dispose (FileEntry.js:125)
    at FileEntry.mv (FileEntry.js:74)
    at Root.unlinkItem (Directory.js:236)
    at Object.Directory.handleWatchEvent [as callback] (Directory.js:61)
    at Root.dispatchWatchEvent (Root.js:455)
```

Do you have any idea what's causing this? Or do you have an example of how to properly to Removals?

Repo: https://github.com/graup/react-aspen-demo/tree/delete-button

**Comment by zikaari** [comment]
I have verified the error and found the cause too, it's [here](https://github.com/NeekSandhu/aspen-decorations/blob/master/src/DecorationManager.ts#L47), the method `delete` isn't bound to the respective `WeakMap` object. I will fix that up soon. But my local test run indicates that this error doesn't prevent the file from being removed from the tree, meaning it doens't appear to be a "fatal error". How is it for you?

**Comment by graup** [comment]
Yeah, you're right, it still works. In our React app, unhandled errors render an error page, so it's unusable there (and I can't catch the error because it's inside a promise in the react-aspen code). A fix would be very appreciated!

**Comment by zikaari** [comment]
Fixed. Rebase on top of `react-aspen-demo#master` to ensure this patch is included - https://github.com/NeekSandhu/react-aspen-demo/commit/aba77d4fb6f7f63412b0da32e1b88e2407243ef9

Here on, the versions must be at least as listed if you never want to see the error again.

BTW can you share how are you guys using `react-aspen` in your product, I might mention it in the readme (unless it's confidential)

**Comment by graup** [comment]
Hi! Thanks, that solved that issue. ~~However, when the component updates afterwards, it seems the deleted item is still in the cache somewhere. As an example, I just call `forceUpdate` [here](https://github.com/graup/react-aspen-demo/commit/bfd391712992663d5a1a88cbc8d8d9808aa26904). In my app, the component is re-rendered at a different point.~~ Never mind, it works if you wait a few miliseconds.

**Comment by graup** [comment]
Ah, we use this in a form to allow users to select a folder inside their S3 bucket. Looks like this. The code is in a private repository but the app is the [Superb AI suite](https://www.superb-ai.com/).

<img width="732" alt="Screen Shot 2020-11-23 at 3 10 51 PM" src="https://user-images.githubusercontent.com/898549/99933355-2a23bd00-2d9e-11eb-8248-fb71783078cc.png">

**Comment by zikaari** [comment]
> ~However, when the component updates afterwards, it seems the deleted item is still in the cache somewhere. As an example, I just call forceUpdate here. In my app, the component is re-rendered at a different point.~

Even though you "solved" it, the reason it's happening is because Root was notified of a "deletion", and it eager applied the change, however, the said item still exists when tree calls `getItems` again on the parent directory. At least this is the case with the setup as it is on `react-aspen-demo`.

In your case, I imagine the deletion happens async over the network, hence the "milliseconds" artifact.

So consider calling `root.inotify` **after** the deletion has really succeeded and you're certain the when the tree calls `getItems` again, the item is not lingering around.

You might be able to fix it up like so:

*perhaps show an indicator while `await` is pending*

```ts
await awsSdk.deleteObject(objPath);
root.inotify(...)
```

**Please check and confirm if this is the issue indeed and if this fix works. If not, I'd like to address this.**

____

> Ah, we use this in a form to allow users to select a folder inside their S3 bucket

Pretty neat, do mind if I mention it in the Readme of `react-aspen`.

**Comment by zikaari** [comment]
Can we close this issue?

**Comment by graup** [comment]
Hi! Yeah, thanks I haven't had any problems anymore. Feel free to mention us if you like!
